-- eLibrary initial PostgreSQL schema.
-- UUID values are generated by the application layer until a database UUID extension is selected.

create type integration_type as enum ('link_only', 'api', 'crawler');
create type integration_status as enum ('planned', 'active', 'degraded', 'disabled');
create type holding_state as enum (
  'available',
  'loaned_out',
  'reservable',
  'owned_unknown',
  'not_owned',
  'login_required',
  'integration_unavailable'
);
create type loan_attempt_state as enum ('created', 'redirect_returned', 'unavailable', 'blocked', 'failed');
create type notification_channel as enum ('email', 'web_push', 'in_app');
create type notification_status as enum ('pending', 'sent', 'failed', 'read');
create type audit_actor_type as enum ('guest', 'member', 'admin', 'system');

create table users (
  id uuid primary key,
  email text not null unique,
  display_name text,
  role text not null check (role in ('member', 'admin', 'system')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table user_preferences (
  user_id uuid primary key references users(id) on delete cascade,
  search_result_layout text not null default 'card' check (search_result_layout in ('card', 'list')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table libraries (
  id uuid primary key,
  name text not null,
  region text,
  operator text,
  eligibility_conditions text,
  homepage_url text,
  ebook_service_url text,
  integration_type integration_type not null default 'link_only',
  integration_status integration_status not null default 'planned',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deactivated_at timestamptz
);

create table user_libraries (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  library_id uuid not null references libraries(id) on delete restrict,
  is_default boolean not null default false,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, library_id)
);

create unique index user_libraries_one_default_per_user
  on user_libraries (user_id)
  where is_default;

create table ebooks (
  id uuid primary key,
  title text not null,
  subtitle text,
  authors text[] not null default '{}',
  publisher text,
  publication_date date,
  isbn13 text,
  isbn10 text,
  description text,
  category text,
  language text,
  cover_image_url text,
  source_library_id uuid references libraries(id) on delete set null,
  external_record_id text,
  adapter_version text,
  fetched_at timestamptz,
  normalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table ebook_aliases (
  id uuid primary key,
  ebook_id uuid not null references ebooks(id) on delete cascade,
  alias_type text not null,
  alias_value text not null,
  source_library_id uuid references libraries(id) on delete set null,
  external_record_id text,
  adapter_version text,
  fetched_at timestamptz,
  normalized_at timestamptz,
  created_at timestamptz not null default now(),
  unique (alias_type, alias_value)
);

create table holdings (
  id uuid primary key,
  ebook_id uuid not null references ebooks(id) on delete cascade,
  library_id uuid not null references libraries(id) on delete restrict,
  source_library_id uuid references libraries(id) on delete set null,
  external_record_id text,
  adapter_version text,
  fetched_at timestamptz,
  normalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (ebook_id, library_id, external_record_id)
);

create table availability_snapshots (
  id uuid primary key,
  holding_id uuid not null references holdings(id) on delete cascade,
  state holding_state not null,
  checked_at timestamptz not null,
  source_library_id uuid references libraries(id) on delete set null,
  external_record_id text,
  adapter_version text,
  fetched_at timestamptz,
  normalized_at timestamptz,
  created_at timestamptz not null default now()
);

create table saved_books (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  ebook_id uuid not null references ebooks(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, ebook_id)
);

create table recent_searches (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  query text not null,
  filters jsonb not null default '{}'::jsonb,
  searched_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table loan_attempts (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  ebook_id uuid not null references ebooks(id) on delete restrict,
  holding_id uuid not null references holdings(id) on delete restrict,
  library_id uuid not null references libraries(id) on delete restrict,
  result_state loan_attempt_state not null,
  redirect_url text,
  normalized_redirect_destination text,
  source_library_id uuid references libraries(id) on delete set null,
  external_record_id text,
  adapter_version text,
  fetched_at timestamptz,
  normalized_at timestamptz,
  attempted_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table notification_preferences (
  user_id uuid primary key references users(id) on delete cascade,
  email_enabled boolean not null default true,
  web_push_enabled boolean not null default true,
  in_app_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table notifications (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  channel notification_channel not null,
  status notification_status not null default 'pending',
  subject text not null,
  body_summary text,
  target_url text,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table push_subscriptions (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  endpoint_hash text not null,
  subscription_ciphertext bytea not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint_hash)
);

create table integration_events (
  id uuid primary key,
  library_id uuid references libraries(id) on delete set null,
  event_type text not null,
  severity text not null check (severity in ('info', 'warning', 'error')),
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table audit_events (
  id uuid primary key,
  actor_type audit_actor_type not null,
  actor_id uuid,
  action text not null,
  target_type text not null,
  target_id text,
  outcome text not null,
  correlation_id text not null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table adapter_configurations (
  library_id uuid primary key references libraries(id) on delete cascade,
  adapter_name text not null,
  adapter_version text not null,
  enabled boolean not null default false,
  api_key_secret_ref text,
  public_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table ebook_search_documents (
  ebook_id uuid primary key references ebooks(id) on delete cascade,
  title text not null,
  authors text[] not null default '{}',
  publisher text,
  isbn_values text[] not null default '{}',
  subjects text[] not null default '{}',
  language text,
  search_vector tsvector not null default ''::tsvector,
  updated_at timestamptz not null default now()
);

comment on table ebook_search_documents is
  'Derived PostgreSQL full-text search projection over public ebook metadata only. Member-owned data must not be stored here.';

create index ebooks_isbn13_idx on ebooks (isbn13);
create index ebooks_isbn10_idx on ebooks (isbn10);
create index ebook_aliases_ebook_id_idx on ebook_aliases (ebook_id);
create index holdings_ebook_id_idx on holdings (ebook_id);
create index holdings_library_id_idx on holdings (library_id);
create index availability_snapshots_holding_checked_idx on availability_snapshots (holding_id, checked_at desc);
create index saved_books_user_id_idx on saved_books (user_id);
create index recent_searches_user_expires_idx on recent_searches (user_id, expires_at);
create index loan_attempts_user_expires_idx on loan_attempts (user_id, expires_at);
create index notifications_user_expires_idx on notifications (user_id, expires_at);
create index integration_events_library_occurred_idx on integration_events (library_id, occurred_at desc);
create index audit_events_occurred_idx on audit_events (occurred_at desc);
create index ebook_search_documents_vector_idx on ebook_search_documents using gin (search_vector);
